apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-registry-ui.fullname" . }}-ui
  labels:
    app: {{ template "docker-registry-ui.name" . }}
    chart: {{ template "docker-registry-ui.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: user-interface
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
      protocol: TCP
      name: http
      {{- if (and (eq .Values.ui.service.type "NodePort") .Values.ui.service.nodePort) }}
      nodePort: {{ .Values.ui.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "docker-registry-ui.name" . }}
    chart: {{ template "docker-registry-ui.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: user-interface
